### ISSUE TITLE
[Bug]: [Regression] MudExSelect shows shadow list

### ISSUE THREAD

**Issue by cdeguise** [fgilde/MudBlazor.Extensions#117]
### What happened?

In upgrading to v8, I noted that the shadow list is now visible. This looks directly related to commit  c26afdbb5fc9c54b84633e086883ef28adbcf1d4. But it's a guess after a quick debug session.

`MudExSelectItem.razor`
```diff
- @inherits MudBaseSelectItem
+ @inherits MudSelectItem<T>

- @if (HideContent == false)
+ @if (true)

```

This issue seems only to present itself when you are using markup to define the select. A simplified test:

```
<MudExSelect T="string" >
    <MudExSelectItem T="string">test</MudExSelectItem>
    <MudExSelectItem T="string">test 2</MudExSelectItem>
</MudExSelect>
```

Shows

![Image](https://github.com/user-attachments/assets/4abc6d6a-0002-48df-8e9d-a07bf8906545)

![Image](https://github.com/user-attachments/assets/d0d3cef2-9874-413d-af0a-7cbf2ed751cb)

### Expected Behavior

I expect only the select control to show and not a visible list of all possible options.

### What application type are you referring to?

ServerRendered

### MudBlazor.Extension Version

8.0

### MudBlazor Version

8.0

### What .net Version are you using?

.Net8

### What browser are you using?

Chrome

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by fgilde** [comment]
Thanks for reporting this issue. I will have a look at it

**Comment by fgilde** [comment]
Fixed in [MudBlazor.Extensions 8.0.1 Nuget](https://www.nuget.org/packages/MudBlazor.Extensions/8.0.1#readme-body-tab)

**Comment by cdeguise** [comment]
@fgilde Turns out the group headers still show but I did validate all the `SelectItem`s are not shwoing. Let me know if you want a new ticket.

**Comment by fgilde** [comment]
I reopened this one. But you can also create a new one I guess that makes more sense.

**Comment by fgilde** [comment]
Can you check with newest preview version? https://www.nuget.org/packages/MudBlazor.Extensions/8.0.2-prev-2501281520-main
